name: build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🧪 Test & lint
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # gives the commit message linter access to all previous commits

      - name: Commit lint
        if: ${{ matrix.php-versions == '8.0' }}
        uses: wagoid/commitlint-github-action@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ast, mbstring, intl
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer:v2

      - name: Deps
        run: composer install --no-interaction

      - name: Quality
        if: matrix.php-versions == '8.0'
        run: |
          vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation
          vendor/bin/phan --no-progress-bar

      - name: Test
        env:
          STREAM_API_KEY: ${{ secrets.STREAM_API_KEY }}
          STREAM_API_SECRET: ${{ secrets.STREAM_API_SECRET }}
        run: vendor/bin/phpunit
